# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 604)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mplwindow = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setObjectName("mplwindow")
        self.mplvl = QtWidgets.QVBoxLayout(self.mplwindow)
        self.mplvl.setObjectName("mplvl")
        self.gridLayout.addWidget(self.mplwindow, 0, 0, 2, 1)
        self.mplfigs = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplfigs.sizePolicy().hasHeightForWidth())
        self.mplfigs.setSizePolicy(sizePolicy)
        self.mplfigs.setMinimumSize(QtCore.QSize(200, 0))
        self.mplfigs.setObjectName("mplfigs")
        self.gridLayout.addWidget(self.mplfigs, 0, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalyze = QtWidgets.QMenu(self.menuBar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        self.menuOverlap_Peaks = QtWidgets.QMenu(self.menuBar)
        self.menuOverlap_Peaks.setObjectName("menuOverlap_Peaks")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAnalyze = QtWidgets.QAction(MainWindow)
        self.actionAnalyze.setObjectName("actionAnalyze")
        self.actionNPA = QtWidgets.QAction(MainWindow)
        self.actionNPA.setObjectName("actionNPA")
        self.actionAR = QtWidgets.QAction(MainWindow)
        self.actionAR.setObjectName("actionAR")
        self.actionCon = QtWidgets.QAction(MainWindow)
        self.actionCon.setObjectName("actionCon")
        self.actionAs_Pb = QtWidgets.QAction(MainWindow)
        self.actionAs_Pb.setObjectName("actionAs_Pb")
        self.actionAs_Br = QtWidgets.QAction(MainWindow)
        self.actionAs_Br.setObjectName("actionAs_Br")
        self.actionAs_Br_2 = QtWidgets.QAction(MainWindow)
        self.actionAs_Br_2.setObjectName("actionAs_Br_2")
        self.actionAsBr = QtWidgets.QAction(MainWindow)
        self.actionAsBr.setObjectName("actionAsBr")
        self.actionAsPb = QtWidgets.QAction(MainWindow)
        self.actionAsPb.setObjectName("actionAsPb")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menuAnalyze.addAction(self.actionAnalyze)
        self.menuAnalyze.addAction(self.actionCon)
        self.menuOverlap_Peaks.addAction(self.actionAsBr)
        self.menuOverlap_Peaks.addAction(self.actionAsPb)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAnalyze.menuAction())
        self.menuBar.addAction(self.menuOverlap_Peaks.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analyze"))
        self.menuOverlap_Peaks.setTitle(_translate("MainWindow", "Overlap Peaks"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAnalyze.setText(_translate("MainWindow", "Analyze"))
        self.actionNPA.setText(_translate("MainWindow", "Net Peak Area"))
        self.actionAR.setText(_translate("MainWindow", "Auto Roi"))
        self.actionCon.setText(_translate("MainWindow", "Standard Concentration"))
        self.actionAs_Pb.setText(_translate("MainWindow", "As (Br)-Pb"))
        self.actionAs_Br.setText(_translate("MainWindow", "As-Br"))
        self.actionAs_Br_2.setText(_translate("MainWindow", "As-Br"))
        self.actionAsBr.setText(_translate("MainWindow", "As-Br"))
        self.actionAsPb.setText(_translate("MainWindow", "As(Br)-Pb"))

